### ISSUE TITLE
Cannot find module 'xunit-file'

### ISSUE THREAD

**Issue by jfstgermain** [peerigon/xunit-file#5]
@peerigon I'm getting this problem with mocha 1.9.0 & xunit-file 0.0.3 both installed locally to my project (works when both are installed globally though)...
Any clue?

```
se@picabo:~/dev/controller-app-bootstrapper$ mocha --reporter xunit-file

module.js:340
    throw err;
          ^
Error: Cannot find module 'xunit-file'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Mocha.reporter (/usr/lib/node_modules/mocha/lib/mocha.js:117:24)
    at Object.<anonymous> (/usr/lib/node_modules/mocha/bin/_mocha:177:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by ashwinaggarwal** [comment]
`node_modules/xunit-file/package.json` has mocha as dev dependencies. So if I had not installed mocha, it was throwing `Error: invalid reporter "xunit-file"`. I went to `node_modules/xunit-file` and ran 'npm install'. It solved my problem.

**Comment by meaku** [comment]
Are you using npm 3.x?

**Comment by ashwinaggarwal** [comment]
Its `2.5.1`
